# Flask {#flask}

## Intro
There seems to be a nice full flask tutorial [here](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world) where a blog is created.

Installation can be done through anaconda.
```{bash eval=FALSE}
conda install -c conda-forge flask
```

Flask code is generally stored within a file called `application.py`. Below is a general framework of the flask code that resides in this file.  
Line 3 is creating a new flask web application.  
Flask applications are designed around routes. On line 5, what is happening is that the code is referring to navigation to the `/` or home directory. The two lines below this route give the code of what to do when a user navigates to that home directory.
```{bash eval=FALSE}
from flask import Flask   
                          
app = Flask(__name__)     
                          
@app.route("/")           
def index():              
    return "Hello, world!"
```

Flask then needs to be told how to import it, by setting the `FLASK_APP` environment variable. If the above code is put into a file called `application.py`, just export that filename. It may be useful if `application.py` is always going to be the main filename to just add this code to the bashrc.
```{bash eval=FALSE}
export FLASK_APP=application.py
```

If flask is run in debug mode, an app will update anytime a change is made to the underlying code.
```{bash eval=FALSE}
export FLASK_ENV=development
```

The web application can then be run by running a flask webserver.
```{bash eval=FALSE}
flask run
```

## Routes
Instead of just using the main route, new routes can be created that when navigated to can have different functionality. In the following example, the route can be accessed at this address: `http://127.0.0.1:5000/david`
```{bash eval=FALSE}
@app.route("/david")
def david():
	return "Hello, David"
```

The route can take the URL addess information dynamically and use it as a variable. In the following example, the text in the URL is being read in as a `string`, and the value is being assigned to the `name` variable.
```{bash eval=FALSE}
@app.route("/<string:name>")
def hello(name):
	name = name.capitalize()
	return "Hello, {}!".format(name)
```

HTML code can also be included in the python code and can be returned and interpreted as HTML. In the following example the text that is getting returned and displayed is being styled as header text on the webpage.
```{bash eval=FALSE}
@app.route("/<string:name>")
def hello(name):
	name = name.capitalize()
	return "<h1>Hello, {}!</h1>".format(name)
```

## Templates
Instead of embedding HTML within values that get returned by python code, HTML files themselves can be served by the python code. Flask can look for HTML files and it will look in a subdirectory of the main directory called `templates`. So in the following example if there is an HTML file called `index.html` within a subdirectory called `templates`, that html file gets served up by the following code.
```{bash eval=FALSE}
@app.route("/")
def index():
    return render_template("index.html")
```

Variables can also be passed from python to the html files that exist within the `templates` directory in order to dynamically alter the HTML content.  
In the following code, the `headline` variable is defined in python and then getting passed to HTML, and it is common that the varible names are just kept the same, though in the return function the second `headline` refers to the python variable and the first to the html variable just as is python methods.
```{bash eval=FALSE}
@app.route("/")
def index():
    headline = "Hello thar"
    return render_template("index.html", headline=headline)
```
Now this `headline` variable can be used in HTML like so. The language being used is Jinja code. This functionality can be helpful in using the very same HTML code but allow it to perform differently.
```{bash eval=FALSE}
<body>
    <h1>{{ headline }}</h1>
</body>
```

## Jinja
Jinja brings programming logic gates to HTML. The code must be put into an html file within the `templates` directory and used by flask as shown in the above templates section.
```{bash eval=FALSE}
<body>
    {% if new_year %}
        <h1>Happy New Year!</h1>
    {% else %}
        <h1>Go back to work</h1>
    {% endif %}
</body>
```

For loops work pretty similar to python as well. In the following code `names` is a python list getting passed from `application.py`, and the list items are rendered as a `ul` in HTML.
```{bash eval=FALSE}
<ul>
    {% for name in names %}
        <li>{{ name }}</li>
    {% endfor %}
</ul>
```

Routes can be referred to by the name of a method within them from HTML. If the following code exists within the `application.py` file:
```{bash eval=FALSE}
@app.route("/more")
def more():
    return render_template("more.html")
```
The above method `more()` just refers to another html file, and this html file can be used from html like so, where the jinja function `url_for` finds the route that contains the `more()` method, and then uses that URL as the link in the `href`.
```{bash eval=FALSE}
<a href="{{ url_for('more') }}">See more...</a>
```

### Inheritance
Inheritance is useful when html code is being repetitively used, as it allows a general layout to be defined and they reused and slightly modified.  
The first part of the example below is how the general layout html can be setup in a file called `layout.html`. In the following code a block is being defined, and the content it uses is whatever is being passed under the variable name `heading`.
```{bash eval=FALSE}
<h1>{% block heading %}{% endblock %}</h1>
```
A separate html file can then inherit all of the html content within `layout.html`, but then add something unique to the black defined above.
```{bash eval=FALSE}
{%extends "layout.html" %}

{% block heading %}
    This is the header
{% endblock %}
```

### Forms
Forms or fields allow input to be captures from the user and then used to perform other functions. In the below example, the `action` is being set as the route that contains teh `hello` method, and the manner in which the information is sent is `post`. The `post` method is different from other methods like the `get` method where information is submitted and a result is returned; may need to read more on this. The `get` method will place the text from the form into the URL. The information being input into the `<input>` field is named `"name"` and this varible can be then passed to `Application.py`.
```{bash eval=FALSE}
<form action="{{ url_for('hello') }}" method="post">
    <input type="text" name="name" placeholder="Enter Your Name"}
    <button>Submit</button>
</form>
```
Within `Application.py` the text that was input into the form is then used to send to `hello.html`. here the `name` variable gets set by using the `form.get` method to retrieve the information, and then the `hello.html` template is rendered by passing the `name` variable tot by using the `form.get` method to retrieve the information, and then the `hello.html` template is rendered by passing the `name` variable to it.
```{bash eval=FALSE}
from flask import Flask, render_template, request

@app.route("/hello", methods=["POST"])             
def hello():                                       
    name = request.form.get("name")                
    return render_template("hello.html", name=name)
```
`hello.html` can then use the `name` variable to display the text entered into the form.
```{bash eval=FALSE}
Hello, {{ name }}!
```

### Sessions
Sessions allow data to be stored, and as long as the webserver is still running (or the data can be saved), and furthermore allows each user to have data that is specific to their individual session.
First `flask_session` needs to be installed.
```{bash eval=FALSE}
pip install flask-session
```

Here in `application.py` a `notes` list is being created to store data that is being input. The route uses both the `get` and `post` methods to get data from the user. And the form sends the `note` variable.  
The `notes` list is created using `session["notes"]` as this will create a list that is stored in a cookie and is specific to the user.
```{bash eval=FALSE}
from flask import Flask, render_template, request, session
from flask_session import Session                         
                                                          
app = Flask(__name__)                                     
                                                          
app.config["SESSION_PERMANENT"] = False                   
app.config["SESSION_TYPE"] = "filesystem"                 
Session(app)                                              
                                                          
@app.route("/", methods=["GET", "POST"])                  
def index():                                              
	if session.get("notes") is None:
		session["notes"] = []       

    if request.method == "POST":                          
        note = request.form.get("note")                   
        notes.append(note)                                
                                                          
    return render_template("index.html", notes=notes)     
```
Then in `index.html` the form is created to send the data to the `application.py` file. And since `notes` is an ever growing list, the list is rendered in the html.
```{bash eval=FALSE}
<ul>                                                             
    {% for note in notes %}                                      
        <li>{{ note }}</li>                                      
    {% endfor %}                                                 
</ul>                                                            
                                                                 
<form action="{{ url_for('index') }}" method="post">             
    <input type="text" name="note" placeholder="Enter Note Here">
    <button>Add Note</button>                                    
</form>                                                          
```
