# SQL {#sql}

## Intro
SQL stands for structured query language that is designed to facilitate accessing data that is structured into table form. PostgreSQL is a version of SQL that is used in these notes.

## Installation
The method I can easily get to work is by installing through `apt`.  
It seems also that for some reason the install only works if the version number is specified.
```{bash eval=FALSE}
sudo apt-get install postgresql-9.6 postgresql-client libpq-dev
```

conda install -c conda-forge psycopg2 flask-sqlalchemy flask-migrate

Both the default database user and default database are called postgres, so switch to that user and start `psql`.
```{bash eval=FALSE}
sudo -u postgres psql
```
Then start a server.
```{bash eval=FALSE}
psql
```

I have not been able to get the installation working through a conda install but here is the reference to postgresql.
```{bash eval=FALSE}
conda install -c conda-forge postgresql
```

To quit `psql` run `\q`.

## Starting Local Database
First set a password for local use.
```{bash eval=FALSE}
sudo -u postgres psql
postgres=# \password
Enter new password:
Enter it again:
postgres=# \q
```

Initially work with localhost to create a database.
```{bash eval=FALSE}
psql -U postgres -W  -h localhost
create database airplanes;
\q
```

Export the location to the newly created database and connect or connect directly.
```{bash eval=FALSE}
export DATABASE_URL="postgresql://localhost/airplanes";
```
or
```{bash eval=FALSE}
psql -U postgres -W  -h localhost postgres://localhost/airplanes
```

## Heroku
Install Heroku.
```{bash eval=FALSE}
sudo snap install --classic heroku
```

Then running any command should prompt to login to Heroku but the `login` command is specific for this.
```
heroku login
```

A sample app from heroku can be cloned to test app deployment.
```
git clone https://github.com/heroku/python-getting-started.git
cd python-getting-started
```

From within the app directory, create the app on heroku. This will create a new app with a random name, but a name can instead be passed to manually set the app name.
```
heroku create
```

The app code can then be committed to the heroku server.
```
git push heroku master
```

Pushing the code will deploy the app, but an instance of the app must be then be run.
```
heroku ps:scale web=1
```

The app can now be visited on the web.
```
heroku open
```

Logs can be viewed of page requests here in a way that will constantly update with each new request.
```
heroku logs --tail
```

The `Procfile` is a file within the root directory of the application that declares the command that should be executed when the app is started. Typically it contains the following.
```
web: gunicorn gettingstarted.wsgi --log-file -
```

### Heroku Dynos
Heroku has some [introduction]('https://devcenter.heroku.com/articles/getting-started-with-python#provision-a-database') to using postgresql with a deployed app. And some more extensive [information]('https://devcenter.heroku.com/articles/heroku-postgresql') as well. It also looks like CS50 has some [instructions]('https://cs50.readthedocs.io/heroku/') as well.

By default heroku apps are deployed to a single dyno which is like a container that runs the commands specified in the `Procfile`. Using a free account will allow a single dyno to be used that will sleep after a half an hour of inactivity. The number of dyno containers can be scaled up and down. If scaled to zero, no containers will run the app.
```
heroku ps:scale web=0
```

The number of free dyno hours is set to 550 per month and with a verified credit card on file will be set to 1000. The remaining time available for a dyno to be running for an app can be checked.
```
heroku ps -a <app-name>
```

To run the heroku test app locally first setup Django to use local assets.
```
python manage.py collectstatic
```

The app can then be run locally at `http://localhost:5000`.
```
heroku local web
```

Changes can be committed in a similar manner as is done with github.
```
git add .
git commit -m 'message'
git push heroku master
```

### Heroku Databases
The current addons including databases available to an app can be viewed.
```
heroku addons
```

The `DATABASE_URL` can be displayed.
```
heroku config
```

More extensive information about the app can also be displayed, includeing the postgres version (PG Version)
```
heroku pg
```

As long as postgresql is installed locally, it is possible to connect to the remote database.
```
heroku pg:psql
```

It is also possible to connect with a database that has just been initiated, where the URI is listed in the `Config Vars` section of the Settings, under `DATABASE_URL`.
```
psql <URI>

```



## Database Hosting With Heroku
1. Navigate to https://www.heroku.com/, and create an account if you don’t already have one.
2. On Heroku’s Dashboard, click “New” and choose “Create new app.”
3. Give your app a name, and click “Create app.”
4. On your app’s “Overview” page, click the “Configure Add-ons” button.
5. In the “Add-ons” section of the page, type in and select “Heroku Postgres.”
6. Choose the “Hobby Dev - Free” plan, which will give you access to a free PostgreSQL database that will support up to 10,000 rows of data. Click “Provision.”
7. Now, click the “Heroku Postgres :: Database” link.
8. You should now be on your database’s overview page. Click on “Settings”, and then “View Credentials.” This is the information you’ll need to log into your database. You can access the database via Adminer, filling in the server (the “Host” in the credentials list), your username (the “User”), your password, and the name of the database, all of which you can find on the Heroku credentials page.
9. Use the URI found in the Settings page of Credentials to link to the database using `export DATABASE_url="URI_URL"`

## Creating a Database
Note that reserved words are all being capitalized below, but this is not required, but rather a stylistic choice.

To create a new database, first run `psql`.
```{bash eval=FALSE}
create database airplanes;
```

Refer to that database.
```{bash eval=FALSE}
export DATABASE_URL="postgresql://localhost/airplanes";
```

List current databases.
```
\list
```

Connect to a new database;
```
\connect airplanes
or
\c airplanes
```

Below is the general syntax to create a PostgreSQL database.  
The `id` is being used in a manner similar to an index that will just number each of the items.  
The next three lines are all different data, and are of types `VARCHAR` and `INTEGER`.  
The `NOT NULL` aspect will cause the server to reject the entry if some data is added to the database but that value is not included.
```{bash eval=FALSE}
CREATE TABLE flights (           
    id SERIAL PRIMARY KEY,       
    origin VARCHAR NOT NULL,     
    destination VARCHAR NOT NULL,
    duration INTEGER NOT NULL    
);                               
```

Display the currently created databases.
```{bash eval=FALSE}
\d
```

Insert data into the flights database.
```{bash eval=FALSE}
INSERT INTO flights (origin, destination, duration) VALUES ('New York', 'London', 415);
```

Select all the data from flights.
```{bash eval=FALSE}
SELECT * FROM flights;
```

Select only the origin and destination columns from flights.
```{bash eval=FALSE}
SELECT origin, destination FROM flights;
```

Select only the data in flights where the id is 3.
```{bash eval=FALSE}
SELECT * FROM flights WHERE id = 3;
```

Select only the data in flights that have an origin of New York.
```{bash eval=FALSE}
SELECT * FROM flights WHERE origin = 'New York';
```

Boolean logic data selection from flights.
```{bash eval=FALSE}
SELECT * FROM flights WHERE destination = 'Paris' AND duration > 500;
```

Average a column of data.
```{bash eval=FALSE}
SELECT AVG(duration) FROM flights;
```

Combine boolean logic with calculations performed on the data.
```{bash eval=FALSE}
SELECT AVG(duration) FROM flights WHERE origin = 'New York';
```

Count columns of matching data.
```{bash eval=FALSE}
SELECT COUNT(*) FROM flights;
```

Select matching data from a list.
```{bash eval=FALSE}
SELECT * FROM flights WHERE origin IN ('New York', 'Lima');
```

Wildcards can be used to search for substrings.
```{bash eval=FALSE}
SELECT * FROM flights WHERE origin LIKE '%a%';
```

SQL uses `LIMIT` to function like `HEAD`.
```{bash eval=FALSE}
SELECT * FROM flights LIMIT 2;
```

Order data in ascending order `asc` is ascending and `desc` is for descending.
```{bash eval=FALSE}
select * from flights order by duration asc;
```

Data can be grouped together as in pandas.  
The following code selects the origin column, counts the number of identical origin entries and then adds this count to a new count column.
```{bash eval=FALSE}
select origin, count(*) from flights group by origin;
```

Grouped data counts can be immedately filtered when searching.
```{bash eval=FALSE}
SELECT origin, COUNT(*) FROM flights GROUP BY origin HAVING COUNT(*) > 1;
```

## Updating Data

This will change the duration of the flight from New York to London to 430.
```{bash eval=FALSE}
UPDATE flights
SET duration = 430
WHERE origin = 'New York'
AND destination = 'London';
```

Delete a set of matching data from a database.
```{bash eval=FALSE}
DELETE FROM flights
WHERE destination = 'Tokyo';
```

## Join/Merge
Inner join is the default join and will only include data that is matched.

Foreign keys can be used to reference the data within another table so that data does not need to be continually repeated. For instance if a number of flights are all heading to New York, the city id could be set as number 1 and then flight destination ids could be just set to 1.  
As an example, the following table can be created that has passenger names, and in the `flight_id` column, the `flights` database is reference to get the actual flight locations.  
When one database references another as in the following code, the referenced column is typically the `PRIMARY KEY`, thought this can be modified if necessary.
```{bash eval=FALSE}
CREATE TABLE passengers(
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    flight_id INTEGER REFERENCES flights);
```

It might be helpful to add some data to the above database for testing, so here is some data.
```{bash eval=FALSE}
INSERT INTO passengers (name, flight_id) VALUES ('Alice', 1);  
INSERT INTO passengers (name, flight_id) VALUES ('Bob', 1);    
INSERT INTO passengers (name, flight_id) VALUES ('Charlie', 2);
INSERT INTO passengers (name, flight_id) VALUES ('Dave', 2);   
INSERT INTO passengers (name, flight_id) VALUES ('Erin', 4);   
INSERT INTO passengers (name, flight_id) VALUES ('Frank', 6);  
INSERT INTO passengers (name, flight_id) VALUES ('Grace', 6);  
```

In order to reference the id data from the `flights` database for instance and match that up with the data found in the `passengers` database, the databases should can be joined on the id columns that correspond with each other, in an analogous manner as is performed in pandas.  
The following code selects the `origin` and `destination` columns from the `flights` database, and the `name` column from the `passengers` database, after the two databases have been joined on their respective flight id columns.
```{bash eval=FALSE}
SELECT origin, destination, name FROM flights JOIN passengers ON passengers.flight_id = flights.id;
```

Data can be directly selected when merging two databases together like the following selection of on the data corresponding with the passenger named `Alice`.
```{bash eval=FALSE}
SELECT origin, destination, name FROM flights JOIN passengers ON passengers.flight_id = flights.id WHERE name = 'Alice';
```

Left/right joining of databases can be performed that unlike inner join will include all of the data in the left or right database.
```{bash eval=FALSE}
SELECT origin, destination, name FROM flights left JOIN passengers ON passengers.flight_id = flights.id WHERE name = 'Alice';
```

## Indexing
Indexing allows a subset of one database (sort of like a pandas series) to be used to select data from a database (analogous to a DataFrame).  
In the following code, within the parentheses the `flight_id` column is being selected to create a "series", and the ids are being grouped by `passengers`, and only those flights have more than one passenger are included within the "series". This series of flight ids is then used to filter the original `flights` "DataFrame".
```{bash eval=FALSE}
select * from flights where id in (select flight_id from passengers group by flight_id having count(*) > 1);
```

## SQL Injection
User input should be escaped or sanitized to prevent a user from inputting SQL code into input fields and have it be directly executed as SQL.  
As an example if a username and password field are presented to the user, and the input is checked against a SQL database, it might look something like the following.
```{bash eval=FALSE}
SELECT * FROM users WHERE (username = 'Bill') AND (password = '12345')
```

The problem with the above code is that SQL code could theoretically be entered into the fields like the following.  
If `1', OR '1' = '1'` is entered into the password field, now the SQL query would looks something like the following, which evaluates as True and may allow somebody access to the database.
```{bash eval=FALSE}
SELECT * FROM users WHERE (username = 'Bill') AND (password = '1', OR '1' = '1')
```

## Transactions and Race Conditions
This refers to a challenge if multiple requests simultaneously are made to the same data within a database and an attempt to modify the database occurs. The problem is that if the requests conflict in some manner the database can be improperly altered. One solution to this is transactions, where one user essentially checks-out the database and can modify it, and the second user can only modify the database after the first user as completed interacting with the database.

## SQLAlchemy
SQLAlchemy is a python library that can be used to interact with SQL data.  
The library can be installed like this:
```{bash eval=FALSE}
conda install -c conda-forge sqlalchemy sqlalchemy-utils
```

SQLAlchemy can be used to interface with an SQL database.
```
from sqlalchemy import create_engine
engine = create_engine(os.getenv("DATABASE_URL"))
```

Users should also be permitted to interact with the SQL database individually within sessions. To do this, a scoped session variable can be created and used to individually interact with the SQL database.
```
from sqlalchemy.orm import scoped_session, sessionmaker
db = scoped_session(sessionmaker(bind=engine))

# this is an example then of interacting with the database
flights = db.execute("SELECT origin, destination, duration FROM flights").fetchall()
for flight in flights:
    print(f"{flight.origin} to {flight.destination}, {flight.duration} minutes.")
```

CSV files can be used to store the information for a database, and inserted into an SQL database.  
Assuming `flights.csv` looks something like this:
```
Paris,New York,540    
Tokyo,Shanghai,185    
Seoul,Mexico City,825 
Mexico City,Lima,350  
Hong Kong,Shanghai,130
```

The following code will then read `flights.csv` and add in the flights to the database.  
`:origin`, `:destination`, and `:duration` define placeholders within the database into which data will be inserted. This placeholder syntax also provides a layer of safety as it helps to prevent users from entering SQL code into a field and directly running SQL.
```
def main():
    f = open("flights.csv")                                                                                        
    reader = csv.reader(f)                                                                                         
    for origin, destination, duration in reader:                                                                   
        db.execute("INSERT INTO flights (origin, destination, duration) VALUES (:origin, :destination, :duration)",
                    {"origin": origin, "destination": destination, "duration": duration})                          
        print(f"Added flight from {origin} to {destination} lasting {duration} minutes.")                          
    db.commit()                                                                                                    
```

Here are some links that may be helpful in setting up an sql database and using it with SQLAlchemy.
[RealPython]('https://realpython.com/flask-by-example-part-2-postgres-sqlalchemy-and-alembic/')
[Location of Postgresql Database]('https://stackoverflow.com/questions/1137060/where-does-postgresql-store-the-database')
[Location of Postgresql Database]('https://stackoverflow.com/questions/26332319/finding-local-postgresql-database-url/51955545')
[CS50 Project1 Help]('https://docs.cs50.net/web/2018/x/projects/1/project1.html')
[Reddit CS50 SQLAlchemy Help]('https://www.reddit.com/r/cs50/comments/bxjafn/sqlalchemy_error_cs50w_lecture_3/')


## Object-Relational Mapping
Python classes can be used to control the function of a SQL database. Typically a Python class can be used to control the functionality in a single SQL database.

Below is an example of a Python class that controls some of the function of an SQL database.  
`__tablename__` refers to the `flights` sql database.  
`db.Model` defines some interactivity with SQLAlchemy and the SQL database.  
`primary_key=True` indicates that this column is used as the primary way to identify the data.  
`db.ForeignKey("flights.id")` references the `flights.id` column within the `Flight` class.
```{bash eval=FALSE}
from flask_sqlalchemy import SQLAlchemy               
                                                      
db = SQLAlchemy()                                     
                                                      
class Flight(db.Model):                               
    __tablename__ = "flights"                         
    id = db.Column(db.Integer, primary_key=True)      
    origin = db.Column(db.String, nullable=False)     
    destination = db.Column(db.String, nullable=False)
    duration = db.Column(db.Integer, nullable=False)  
    passengers = db.relationship("Passenger", backref="flight", lazy=True)

class Passenger(db.Model):                                                        
    __tablename__ = "passengers"                                                  
    id = db.Column(db.Integer, primary_key=True)                                  
    name = db.Column(db.String, nullable=False)                                   
    flight_id = db.Column(db.Integer, db.ForeignKey("flights.id"), nullable=False)
```

Creating a class in the above manner will allow modification of an SQL database using just python with SQLAlchemy. This avoids the requirement of using SQL commands explicitly within the code.  
The following is an example of adding flight data to a database using the Flight class.
```{bash eval=FALSE}
db.init_app(app)
flight = Flight(origin=origin, destination=destination, duration=duration)
db.session.add(flight)                                                    
db.session.commit()
```

A SQL database can also be queried with python instead of SQL commands.  
The first command below is how a SQL database can be queried with SQL syntax and the second is with python using SQLAlchemy.
```{bash eval=FALSE}
# using SQL
flights = db.execute("SELECT origin, destination, duration FROM flights").fetchall()

# using SQLAlchemy
flights = Flight.query.all()
```

Filtering can also be done with similar code.
```{bash eval=FALSE}
flights = Flight.query.filter_by(origin="Paris").first()
```

Results can be counted.
```{bash eval=FALSE}
flights = Flight.query.filter_by(origin="Paris").count()
```

Data can be retrieved by its ID, where the below code gets the row with ID 28.
```{bash eval=FALSE}
Flight.query.get(28)
```

Data within a table can be modified.  
The following code gets the row with an ID of 6 then updates its duration to 280.
```{bash eval=FALSE}
flight = Flight.query.get(6)
flight.duration = 280
```

Data can be deleted from a table.
```{bash eval=FALSE}
flight = Flight.query.get(6)
db.session.delete(flight)
```

Data from a table can be retrieved and ordered.
```{bash eval=FALSE}
Flight.query.order_by(Flight.origin.desc()).all()
```

Table data can be retrieved when it does not match a boolean expression.
```{bash eval=FALSE}
Flight.query.filter(
    Flight.origin != "Paris").all()
```

SQL substring querying can be performed with SQLAlchemy.
```{bash eval=FALSE}
Flight.query.filter(
    Flight.origin.like("%a%")).all()
```

SQL search can be performed using a list of values.
```{bash eval=FALSE}
Flight.query.filter(
    Flight.origin.in_(
        ["Tokyo", "Paris"])).all()
```

Boolean expressions can be used.
```{bash eval=FALSE}
Flight.query.filter(
    or_(Flight.origin == "Paris",
        Flight.duration > 500)).all()
```

Tables can be joined together.
```{bash eval=FALSE}
db.session.query(Flight, Passenger).filter(
    Flight.id == Passenger.flight_id).all()
```

## APIs
API stands for application programming interface.  
JSON stands for Javascript object notation.  

There are a number of different HTTP request types.  
GET: retrieve a resource  
POST: create a new resource  
PUT: replace a resource  
PATCH: update a resource  
DELETE: delete a resource  

The python library `requests` enables requesting from python. Below is a get request which grabs the html code from google.com.
```{bash eval=FALSE}
import requests
res = requests.get("https://www.google.com/")
print(res.text)                              
```

API calls should return status codes that classify the status of the request.  
Status codes are as follows:  
200: OK  
201: Created  
400: Bad Request  
403: Forbidden  
404: Not Found  
405: Method Not Allowed  
422 Unprocessable Entity
```{bash eval=FALSE}
res = requests.get("https://api.fixer.io/latest?base=USD&symbols=EUR")
if res.status_code != 200:                                            
    raise Exception("ERROR: API request unsuccessful.")               
    data = res.json()                                                     
    print(data)                                                           

```

An API can be designed to return a JSON object that contains some of the information from the site.  
In flask the `application.py` can use the following code to accomplish this.
```{bash eval=FALSE}
from flask import jsonify

@app.route("/api/flights/<int:flight_id>")                 
def flight_api(flight_id):                                 
    """Return details about a single flight."""            
                                                           
    # Make sure flight exists.                             
    flight = Flight.query.get(flight_id)                   
    if flight is None:                                     
        return jsonify({"error": "Invalid flight_id"}), 422
                                                           
    # Get all passengers.                                  
    passengers = flight.passengers                         
    names = []                                             
    for passenger in passengers:                           
        names.append(passenger.name)                       
    return jsonify({                                       
            "origin": flight.origin,                       
            "destination": flight.destination,             
            "duration": flight.duration,                   
            "passengers": names                            
        })                                                 
```
