# Javascript {#javascript}

## Intro
FYI Ctrl+Shift+I in chrome opens the console. In the console commands can be entered and variables can be used that have been defined in the page. Variables can also be modified from this console as well.

The `<script>` tags within the `<head>` is where javascript can be put.
```{bash eval=FALSE}
<head>
    <script>
        alert('Hello');
    </script>
</head>
```

## Event Handling
There a number of event handlers in Javascript, and here are a few:  
```{bash eval=FALSE}
onclick
onmouseover
onkeydown
onkeyup
onload
onblur
```

The following code creates a button that runs the `hello()` function only when the button is clicked.
```{bash eval=FALSE}
<head>
    <script>
        function hello() {
            alert('Hello!');
        }
    </script>
</head>
<body>
    <button onclick="hello()">Click Here</button>
</body>
```

Javascript can be used to change the contents of the html within a page.  
In the following code, the `querySelector` searches for the first `h1` tag on the page, and then uses the `innerHTML` method to modify the contents within that tag.
```{bash eval=FALSE}
<style>
    <script>
        function hello() {                                      
            document.querySelector('h1').innerHTML = 'Goodbye!';
            }                                                       
    </script>
</style>
<body>
    <h1>Welcome!</h1>                             
    <button onclick="hello()">Click Here!</button>
</body>
```

`querySelector` can also select by id or class.
```{bash eval=FALSE}
document.querySelector('tag')
document.querySelector('#id')
document.querySelector('.class')
```

Here is an example that uses the `id` to control its contents.
```{bash eval=FALSE}
<style>
    <script>
		counter = 0;                                               
																   
		function count() {                                         
			counter++;                                             
			document.querySelector('#counter').innerHTML = counter;
		}                                                          
    </script>
</style>
<body>
	<h1 id="counter">0</h1>                       
	<button onclick="count()">Click Here!</button>
</body>
```

Template literals allow variables to be used within a string.
```{bash eval=FALSE}
if (counter % 10 === 0) {              
    alert(`Counter is at ${counter}!`);
}                                      
```

The necessary javascript can be separated out of a page and included in a `something.js` file and then referenced within an html file.  
```{bash eval=FALSE}
<head>                                 
    <script src="something.js"></script>
</head>                                
```

## Variables
`const` can not be redefined.  
`let` has block scope so it only exists within a block defined by `{}`.  
`var` exists within the function in which it is defined.  

## Event Listeners
Event listeners can be run only when the DOM is loaded, and can listen for events within the html document. This can be a helpful way of offloading some of the work from the html onto javascript.  
Below is an example of using javascript to control the function of a button using a callback function.  
In the following code, the `addEventListener` takes two input variables, the first is `DOMContentLoaded` which triggers the listener to start processing after the page has loaded. For the second parameter, whatever should be triggered is passed. Below, the second parameter is an entire function being passed in, and it selects the first button, and runs the count method on a click event.
```{bash eval=FALSE}
<head>
    <script>
		document.addEventListener('DOMContentLoaded', function() { 
			document.querySelector('button').onclick = count;      
		});                                                        
																   
		let counter = 0;                                           
																   
		function count() {                                         
			counter++;                                             
			document.querySelector('#counter').innerHTML = counter;
																   
			if (counter % 10 === 0) {                              
				alert(`Counter is at ${counter}!`);                
			}                                                      
		}                                                          
    </script>
</head>
<body>
	<h1 id="counter">0</h1>     
	<button>Click Here!</button>
</body>
```

An event listener can be used to pull the contents of a field when a button is pressed.
```{bash eval=FALSE}
<head>                                                                               
    <script>                                                                         
        document.addEventListener('DOMContentLoaded', function() {                   
            document.querySelector('#form').onsubmit = function() {                  
                const name = document.querySelector('#name').value;                  
                alert(`Hello ${name}!`);                                             
            };                                                                       
        });                                                                          
    </script>                                                                        
    <title>My Website</title>                                                        
</head>                                                                              
<body>                                                                               
    <form id="form">                                                                 
        <input id="name" autocomplete="off" autofocus placeholder="Name" type="text">
        <input type="submit">                                                        
    </form>                                                                          
</body>                                                                              
```

CSS styling can be changed using javascript event listeners.
```{bash eval=FALSE}
document.querySelector('#red').onclick = function() {    
    document.querySelector('#hello').style.color = 'red';
};                                                       
```

Event listeners can be generalized and used for multiple elements using the `dataset` property.  
In the following code, `document.querySelectorAll('.color-change')` selects all of the buttons that belong ot hte `color-change` class.  
The `forEach` method loops through the array of all of the buttons.  
Then the onclick method uses `button.dataset.color` to reference the `data-color="red"` part of each button to set the color of the text defined by `id="hello"`.  
The `data-color="red"` of each button can be set to anything else that follows the pattern `data-*` and then can be referenced with `button.dataset.*`.
```{bash eval=FALSE}
<head>                                                                                  
    <script>                                                                            
        document.addEventListener('DOMContentLoaded', function() {                      
                                                                                        
            // Have each button change the color of the heading                         
            document.querySelectorAll('.color-change').forEach(function(button) {       
                button.onclick = function() {                                           
                    document.querySelector('#hello').style.color = button.dataset.color;
                };                                                                      
            });                                                                         
                                                                                        
        });                                                                             
    </script>                                                                           
    <title>My Website</title>                                                           
</head>                                                                                 
<body>                                                                                  
    <h1 id="hello">Hello!</h1>                                                          
    <button class="color-change" data-color="red">Red</button>                          
    <button class="color-change" data-color="blue">Blue</button>                        
    <button class="color-change" data-color="green">Green</button>                      
</body>                                                                                 
```

### Arrow Functions
Arrow functions are new to ES6 and abbreviate the manner in which functions are created.  
Below a function is created that creates the Hellow World alert.
```{bash eval=FALSE}
() => {
	alert('Hello world!');
}
```

Below is a function that takes as input the variable `x`.
```{bash eval=FALSE}
x => {
	alert(x);
}
```

An even more succinct manner of writing a function is below.
```{bash eval=FALSE}
x => x * 2;
```

Below is an example of the above code re-written to use arrow functions.
```{bash eval=FALSE}
<script>                                                                            
    document.addEventListener('DOMContentLoaded', () => {                           
                                                                                    
        // Have each button change the color of the heading                         
        document.querySelectorAll('.color-change').forEach(button => {              
            button.onclick = () => {                                                
                document.querySelector('#hello').style.color = button.dataset.color;
            };                                                                      
        });                                                                         
                                                                                    
    });                                                                             
</script>                                                                           
```

## Adding to the DOM











